#!/usr/bin/env bash

# This file is autogenerated
#
# Modifications done to this file will only affect this game server instance.
# Any changes made to this file will be overwritten if the file is regenerated.
# KGSM will not regenerated this file on its own, but there is a command that
# can be manually used to regenerate the file in case something breaks:
# > $KGSM_ROOT/commands/files.sh management create <instance>

# Disabling SC2154 globally:
# $instance_* variables are set dynamically from the config file
# check "__source_instance_config"
# shellcheck disable=SC2154
